# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4
    executor: ruby/default
    working_directory: /tmp
    steps:
      - run: |
          mkdir javaexec
          cd javaexec
          curl -LJO https://github.com/wrbejar/Javafiles/java > /tmp/java
          cd /tmp
          pwd
          ls -l
      - store_artifacts:
           path: /tmp
           destination: java 
      - run: |
           pwd
           ls

      - run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar --output ./wss-unified-agent.jar
          pwd
          ls
      - store_artifacts:
           path: ./
           destination: wss-unified-agent.jar
      - run: |
          pwd
          ls
      - run: |
          cd /tmp
          ls -l
          sudo chmod 777 java
          ls -l
#          - run: sudo java -jar ./wss-unified-agent.jar apiKey edf10bdd3442429aaf134d300e98c9621ce1f079cd094591a11c91f8f0decab3 product RubyOdinFromCircleCI
     