# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4
    executor: ruby/default
    working_directory: /tmp
    steps:
      - run: |
          curl -LJO https://drive.google.com/file/d/1chc3wFYj5DPwWre19q_zmhb9W823L1sg/view?usp=sharing --output /tmp/java.exe
          cd /tmp/
          pwd
          ls
      - store_artifacts:
           path: /tmp/
           destination: java.exe
      - run: |
          pwd
          ls
      - run: |
          curl -LJO https://drive.google.com/file/d/1chc3wFYj5DPwWre19q_zmhb9W823L1sg/view?usp=sharing --output /tmp/java.exe
          cd /tmp/
          pwd
          ls
      - store_artifacts:
           path: /tmp/
           destination: java.exe
      - run: |
          pwd
          ls    
      - run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar --output /tmp/wss-unified-agent.jar
          cd /tmp/
          pwd
          ls
      - store_artifacts:
           path: /tmp/
           destination: wss-unified-agent.jar
      - run: |
          pwd
          ls
      - run: |
          /tmp/java -jar wss-unified-agent.jar apiKey edf10bdd3442429aaf134d300e98c9621ce1f079cd094591a11c91f8f0decab3 product RubyOdinFromCircleCI


    
      