name: Whitesource Unified Agent Scan - Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'      
      - name: WhiteSource Unified Agent Scan
        env:
          WS_APIKEY: ${{secrets.APIKEY}}
          WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
          WS_PRODUCTNAME: RubyTheOdinProject
          WS_PROJECTNAME: RubyTheOdinProject
        run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          echo Unified Agent downloaded successfully
          java -jar wss-unified-agent.jar
